### ISSUE TITLE
Error al cargar el favicon de la web

### ISSUE THREAD

**Issue by paurealm** [frostedana8/pajas.cum#1]
Cuando entro a la web, el favicon es una Yuumi y la verdad es que creo que es un bug porque no puede ser que me hayáis cargado una foto del dichoso parásito ese en mi navegador. O sea, me parece un insulto. Espero que lo solucionéis pronto
![image](https://user-images.githubusercontent.com/67194268/197420855-360fdfb1-648a-4076-a02a-9d8adf299c19.png)

**Comment by frostedana8** [comment]
![hfeaifesif4hfiw4yh8](https://user-images.githubusercontent.com/36996739/208204819-15716506-18f1-4e11-83c2-73a4a842701a.png)

**Comment by paurealm** [comment]
please reopen, can confirm in 1.5
